In [1]:
import torch
import torch.nn as nn
from torch.nn.modules.module import Module
import numpy as np
# from .models.normal_head import NormalHead
# from .models.translayer import Transformer

In [2]:
a = torch.randn(3,4,2)
print(f"==>> a.shape: {a.shape}")

==>> a.shape: torch.Size([3, 4, 2])


In [4]:
b = torch.full_like(a, True, dtype=torch.bool)
print(f"==>> b: {b}")

==>> b: tensor([[[True, True],
         [True, True],
         [True, True],
         [True, True]],

        [[True, True],
         [True, True],
         [True, True],
         [True, True]],

        [[True, True],
         [True, True],
         [True, True],
         [True, True]]])


In [2]:
abn_distance = torch.randn(30, 200)
print(f"==>> abn_distance.shape: {abn_distance.shape}")

==>> abn_distance.shape: torch.Size([30, 200])


In [3]:
mask_select_abnormal_sample = torch.zeros_like(abn_distance, dtype=torch.bool)
print(f"==>> mask_select_abnormal_sample.shape: {mask_select_abnormal_sample.shape}")
mask_select_abnormal_sample[0, :10]

==>> mask_select_abnormal_sample.shape: torch.Size([30, 200])


tensor([False, False, False, False, False, False, False, False, False, False])

In [5]:
topk_abnormal_sample = torch.topk(abn_distance, int(200*0.2), dim=-1)
print(f"==>> topk_abnormal_sample: {topk_abnormal_sample}")

==>> topk_abnormal_sample: torch.return_types.topk(
values=tensor([[2.9937, 2.3604, 2.0455,  ..., 0.8039, 0.7743, 0.7711],
        [2.8203, 2.5688, 2.5275,  ..., 1.0888, 1.0666, 1.0640],
        [2.8296, 2.0380, 1.9279,  ..., 0.8469, 0.8440, 0.8312],
        ...,
        [2.9432, 2.7953, 2.7763,  ..., 1.0149, 0.9712, 0.9599],
        [2.5647, 2.1438, 1.9623,  ..., 0.6684, 0.6629, 0.6533],
        [2.1054, 2.0460, 2.0309,  ..., 0.7430, 0.6978, 0.6787]]),
indices=tensor([[182,  66,  53,  ..., 135,  65,  20],
        [155, 163,  33,  ..., 115,  11, 118],
        [ 78,  28, 111,  ..., 168,  49,  20],
        ...,
        [139,  17,  22,  ...,  45, 159,  37],
        [ 78, 196,  58,  ..., 102,  83, 132],
        [ 34, 146, 101,  ..., 105,  76, 174]]))


In [6]:
topk_abnormal_sample = torch.topk(abn_distance, int(200*0.2), dim=-1)[1]
print(f"==>> topk_abnormal_sample.shape: {topk_abnormal_sample.shape}")

==>> topk_abnormal_sample.shape: torch.Size([30, 40])


In [8]:
topk_abnormal_sample[0]

tensor([182,  66,  53,  15, 157, 102, 178,  47, 113,  21,  74,   3, 136, 143,
         55, 150, 146, 139, 193,  45,   5, 183,  60,   0, 191, 140,  78,  32,
         34, 130, 149,  77,  52,  58, 116, 148, 169, 135,  65,  20])

In [7]:
mask_select_abnormal_sample.scatter_(1, topk_abnormal_sample, True)
mask_select_abnormal_sample[0]

tensor([ True, False, False,  True, False,  True, False, False, False, False,
        False, False, False, False, False,  True, False, False, False, False,
         True,  True, False, False, False, False, False, False, False, False,
        False, False,  True, False,  True, False, False, False, False, False,
        False, False, False, False, False,  True, False,  True, False, False,
        False, False,  True,  True, False,  True, False, False,  True, False,
         True, False, False, False, False,  True,  True, False, False, False,
        False, False, False, False,  True, False, False,  True,  True, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False,  True, False, False, False, False, False, False, False,
        False, False, False,  True, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, 

In [9]:
print(f"==>> mask_select_abnormal_sample.shape: {mask_select_abnormal_sample.shape}")

==>> mask_select_abnormal_sample.shape: torch.Size([30, 200])


In [10]:
feats = torch.randn(30*200, 512 // 32)
print(f"==>> feats.shape: {feats.shape}")

==>> feats.shape: torch.Size([6000, 16])


In [11]:
selected_feats = feats[mask_select_abnormal_sample.reshape(-1)]
# mask_select_abnormal_sample는 True 1200개 False 4800개
print(f"==>> selected_feats.shape: {selected_feats.shape}")

==>> selected_feats.shape: torch.Size([1200, 16])


In [12]:
t_m = torch.mean(torch.randn(32,10,200), dim=1)
print(f"==>> t_m.shape: {t_m.shape}")

==>> t_m.shape: torch.Size([32, 200])


In [4]:
a = np.array([1,2,3,4,5])
print(f"==>> a: {a}")

==>> a: [1 2 3 4 5]


In [5]:
np.save("test", a)

In [6]:
a_l = np.load("test.npy")
print(f"==>> a_l: {a_l}")

==>> a_l: [1 2 3 4 5]


In [7]:
a2 = np.array([[1,2,3],[4,5,6]])
print(f"==>> a2: {a2}")

==>> a2: [[1 2 3]
 [4 5 6]]


In [8]:
np.save("test", a2)

In [9]:
a_l = np.load("test.npy")
print(f"==>> a_l: {a_l}")

==>> a_l: [[1 2 3]
 [4 5 6]]


In [10]:
tttt = torch.randn(2,3,4)
print(f"==>> tttt.shape: {tttt.shape}")

==>> tttt.shape: torch.Size([2, 3, 4])


In [11]:
ttttt = tttt.mean(dim=1)
print(f"==>> ttttt.shape: {ttttt.shape}")

==>> ttttt.shape: torch.Size([2, 4])
